#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 17 15:59:26 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
